# Generated by Django 2.0.1 on 2019-09-09 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(verbose_name='编码')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('grade', models.IntegerField(default=1, verbose_name='等级')),
                ('picture_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='图片路径')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.CategoryModel', verbose_name='父类')),
            ],
            options={
                'verbose_name': '分类表',
                'verbose_name_plural': '分类表',
                'db_table': 't_category',
            },
        ),
        migrations.CreateModel(
            name='CommodityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodityName', models.CharField(max_length=200, verbose_name='商品名称')),
                ('state', models.IntegerField(choices=[(0, '无货'), (1, '有货')], verbose_name='商品状态')),
                ('sellPrice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='销售价格')),
                ('maxCommodityCount', models.IntegerField(blank=True, null=True, verbose_name='库存')),
                ('sales', models.IntegerField(blank=True, null=True, verbose_name='销量')),
                ('spec', models.CharField(max_length=50, verbose_name='商品规格')),
                ('field', models.CharField(max_length=100, verbose_name='产地')),
                ('iframepage', models.CharField(blank=True, max_length=400, null=True, verbose_name='图文详情')),
                ('smallPicture', models.CharField(max_length=400, verbose_name='商品小图')),
                ('showPicture', models.CharField(max_length=400, verbose_name='商品展示图片')),
                ('subTitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='商品二级标题')),
                ('canAddCart', models.BooleanField(verbose_name='能否加入购物车')),
                ('canNoReasonToReturnText', models.CharField(blank=True, default='不支持7天无理由退货', max_length=100, null=True)),
                ('deliveryTips', models.CharField(blank=True, default=' 16:00 前完成订单，预计明日送达', max_length=100, null=True)),
                ('categoryName', models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', to='goods.CategoryModel', verbose_name='分类名')),
            ],
            options={
                'verbose_name': '商品信息表',
                'verbose_name_plural': '商品信息表',
                'db_table': 't_commodity',
            },
        ),
    ]
