# Generated by Django 2.0.1 on 2019-09-09 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryEntity',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='编码')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('grade', models.IntegerField(default=1, verbose_name='等级')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.CategoryEntity')),
            ],
            options={
                'verbose_name': '分类表',
                'verbose_name_plural': '分类表',
                'db_table': 't_category',
            },
        ),
    ]
