# Generated by Django 2.0.1 on 2019-09-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commoditymodel',
            name='categoryName',
        ),
        migrations.AddField(
            model_name='commoditymodel',
            name='categoryId',
            field=models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', to='goods.CategoryModel', verbose_name='分类id'),
        ),
        migrations.AlterField(
            model_name='commoditymodel',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
