# Generated by Django 2.0.1 on 2019-09-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190910_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commoditymodel',
            old_name='iframepage',
            new_name='iframePage',
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='code',
            field=models.CharField(max_length=20, verbose_name='编码'),
        ),
        migrations.AlterField(
            model_name='commoditymodel',
            name='canAddCart',
            field=models.BooleanField(default=True, verbose_name='能否加入购物车'),
        ),
        migrations.AlterField(
            model_name='commoditymodel',
            name='state',
            field=models.IntegerField(choices=[(0, '无货'), (1, '有货')], default=1, verbose_name='商品状态'),
        ),
    ]
