# Generated by Django 2.0.1 on 2019-09-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20190910_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoditymodel',
            name='field',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='产地'),
        ),
    ]
