# Generated by Django 2.0.1 on 2019-09-10 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20190910_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoditymodel',
            name='categoryId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.CategoryModel', verbose_name='分类id'),
        ),
    ]
