# Generated by Django 2.0.1 on 2019-09-11 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190911_1711'),
        ('goods', '0004_auto_20190910_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponModel',
            fields=[
                ('couponCode', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='优惠券号')),
                ('couponName', models.CharField(max_length=50, verbose_name='优惠券名称')),
                ('couponMoney', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='优惠金额或折扣')),
                ('couponType', models.IntegerField(verbose_name='优惠券类型')),
                ('LimitPrice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='优惠的价格上限/门槛')),
                ('giveoutTime', models.DateTimeField(verbose_name='发放时间')),
                ('validTime', models.DateTimeField(verbose_name='有效时间')),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.UserModel', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '优惠券类型',
                'verbose_name_plural': '优惠券类型',
                'db_table': 't_coupon',
            },
        ),
    ]
