# Generated by Django 2.0.1 on 2019-09-16 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_couponmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponmodel',
            old_name='userId',
            new_name='user',
        ),
    ]
