# Generated by Django 2.0.1 on 2019-09-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('activeName', models.CharField(max_length=50, verbose_name='活动名称')),
                ('pictureUrl', models.CharField(max_length=50, verbose_name='图片地址')),
                ('linkUrl', models.CharField(max_length=50, verbose_name='链接地址')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'db_table': 't_active',
            },
        ),
        migrations.CreateModel(
            name='NavlistModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('navName', models.CharField(max_length=50, verbose_name='导航名称')),
                ('navPictureUrl', models.CharField(max_length=50, verbose_name='图片地址')),
                ('navLinkUrl', models.CharField(max_length=50, verbose_name='链接地址')),
            ],
            options={
                'verbose_name': '推荐导航',
                'verbose_name_plural': '推荐导航',
                'db_table': 't_navlist',
            },
        ),
        migrations.CreateModel(
            name='TemplateModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('templateName', models.CharField(max_length=50, verbose_name='模板名称')),
                ('templateHtml', models.CharField(max_length=20, verbose_name='模板网页')),
            ],
            options={
                'verbose_name': '模板类型',
                'verbose_name_plural': '模板类型',
                'db_table': 't_temp',
            },
        ),
    ]
