# Generated by Django 2.0.1 on 2019-09-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoditycart',
            name='is_choice',
            field=models.BooleanField(default=False, verbose_name='选中状态'),
        ),
    ]
