# Generated by Django 2.0.1 on 2019-09-16 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='user_id',
            new_name='user',
        ),
    ]
