# Generated by Django 2.0.1 on 2019-09-10 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartmodel',
            options={'verbose_name': '购物车', 'verbose_name_plural': '购物车'},
        ),
    ]
