# Generated by Django 2.0.1 on 2019-09-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='用户ID'),
        ),
    ]
