# Generated by Django 2.0.1 on 2019-09-09 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('AreaName', models.CharField(max_length=20, verbose_name='地区名')),
            ],
            options={
                'verbose_name': '地区',
                'verbose_name_plural': '地区',
                'db_table': 't_area',
            },
        ),
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=20, verbose_name='城市名')),
                ('firstChar', models.CharField(max_length=2, verbose_name='首字母')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
                'db_table': 't_city',
            },
        ),
        migrations.AddField(
            model_name='areamodel',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area', to='order.CityModel'),
        ),
    ]
