# Generated by Django 2.0.1 on 2019-09-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190910_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='citymodel',
            name='hotcity',
            field=models.IntegerField(blank=True, choices=[(0, '否'), (1, '是')], default=0, null=True, verbose_name='热门城市'),
        ),
    ]
