# Generated by Django 2.0.1 on 2019-09-12 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_couponmodel'),
        ('order', '0004_citymodel_hotcity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area_commodityModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area', to='order.AreaModel', verbose_name='地区')),
                ('commodity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commodity', to='goods.CommodityModel', verbose_name='商品')),
            ],
            options={
                'verbose_name': '地区商品',
                'verbose_name_plural': '地区商品',
                'db_table': 't_area_commodity',
            },
        ),
    ]
