# Generated by Django 2.0.1 on 2019-09-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_area_commoditymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('privName', models.CharField(max_length=20, verbose_name='省份')),
                ('cityName', models.CharField(max_length=20, verbose_name='城市')),
                ('streetName', models.CharField(max_length=20, verbose_name='街道')),
                ('specify', models.CharField(max_length=50, verbose_name='详细地址')),
            ],
            options={
                'verbose_name': '收货地址',
                'verbose_name_plural': '收货地址',
                'db_table': 't_address',
            },
        ),
    ]
